### ISSUE TITLE
AuthorizationApi question

### ISSUE THREAD

**Issue by gokigoks** [jlevers/selling-partner-api#105]
Thank you for the package. The documentation is truly top-notch.

Just wanted to clarify something about the AuthorizationApi. We have an existing MWS app and being able to use the Auth made from mws to SP-API is a must for us. 

Our question is, The AuthorizationAPI is supposed to return an LWA authorization code used to get refresh tokens, however, one of the config parameters in this request also includes refresh_token. We would really appreciate it if this can be clarified. Where do we get the LWA refresh token for this request?

Thank you again for your time and effort on this amazon package. It has saved us a lot of time and headaches.

**Comment by jlevers** [comment]
Hey @gokigoks, I appreciate the kind words!

You shouldn't have to pass the refresh token when calling `AuthorizationApi::getAuthorizationCode`. Sorry if my documentation is misleading about how that works. What happens if you just don't provide a `refresh_token` parameter when initializing the `Configuration` object that you pass to your `AuthorizationApi` instance?

**Comment by gokigoks** [comment]
Hi @jlevers,

Thank you for the response to a non-issue ticket. I actually receive a sensible response "No app id" which I believe is due to my app still being on draft status. So you're probably right that the getAuthorization request does not need a refresh token parameter. 

Thank you again! I'll close this issue now.

**Comment by jlevers** [comment]
Yep, that's correct -- the `getAuthorizationCode` call only works with published apps.
