### ISSUE TITLE
Get information about custom or personalized item in order...

### ISSUE THREAD

**Issue by moiloal** [jlevers/selling-partner-api#145]
Hi again, I have a question about order's items response.

I make the call to getOrderItems but it not appears in the response custom information of the product. if the product is custom or personalized, for example the name of a personalized mug it not appears in response of getOrderItems. I can't automatize it and I need to enter in the admin panel of Amazon Seller to check this information, but I want to receive it in my custom panel, printer labels and in the delivery note.

Can you help me please?.

Thank you very much in advance for your help.

**Comment by jlevers** [comment]
The custom order item info only comes back if you pass the `buyerInfo` data element to the `getOrderItems` call, like so:

```php
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Api\OrdersApi;

$config = new Configuration([/* .... */]);
$api = new OrdersApi($config);
$response = $api->getOrderItems($orderId, null, ['buyerInfo']);
```

You might need access to one of the restricted roles that provide PII in order to be able to access `buyerInfo`-specifc data on order items, but I'm not entirely sure -- give the above code a try and see if it works for you. If you get a 403 error, then you need PII access to get custom order item info.

**Comment by jlevers** [comment]
@moiloal since it's been a week and I haven't heard from you, I'm going to assume you figured out the issue. I'm closing the issue, but feel free to reopen it if you need more help.
