### ISSUE TITLE
ShipmentId Issue

### ISSUE THREAD

**Issue by philmccarty** [jlevers/selling-partner-api#149]
I'm having a bit of a problem where I (believe) I successfully call **createInboundShipmentPlan** which gives me a shipmentId,
but then when I turnaround and call **createInboundShipment** with same shipmentId, moments later, despite it having the same items and quantities,  I receive the following error: 

"Error: You must include a valid ShipmentId with a call to the CreateInboundShipment operation. Get ShipmentId values by calling the CreateInboundShipmentPlan operation. The request to CreateInboundShipment must include only items and quantities that have been previously planned through CreateInboundShipmentPlan. If a ShipmentId is not used to create a shipment within 48 hours it will expire."

This might not be an API issue and might be something I',m doing wrong in sequence, I simply can't tell from this end.

**Comment by jlevers** [comment]
Hey @philmccarty --

I haven't worked with `createInboundShipmentPlan` myself, but that problem sounds like one that's likely on Amazon's end, rather than being related to this library. I recommend creating an issue in [Amazon's documentation repo](https://github.com/amzn/selling-partner-api-docs/issues), or opening a support case on Seller Central.

Sorry I can't be of more help here, but I'm 99% sure this isn't related to my library :)

**Comment by w00dface79** [comment]
I went around in circles with the same issue (I know i'm posting 2 years later, but in-case anyone else has the same problem...)

Once you have made the shipment plan, you have to then create the shipment before you can do anything else.
