### ISSUE TITLE
Cannot call report GET_ORDER_REPORT_DATA_INVOICING

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#163]
Hi jlevers,
I have account  on seller
I used your library call  report GET_FLAT_FILE_OPEN_LISTINGS_DATA,
 it work well but when I called GET_ORDER_REPORT_DATA_INVOICING it said errors in debug  
  "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
Please help how to fix it?
Thanks jlevers

**Comment by thugic** [comment]
That report may contain PII (Personally identifiable information) and Amazon restricts usage of those as much as possible. In order to enable the report, you must ask for authorisation on the Amazon dashboard (iirc it's the one about financial data)

**Comment by jlevers** [comment]
Yep, as @thugic said above -- that report type is in the list of [restricted report types](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#restricted-report-types), so you'll need PII access in order to request it.

**Comment by dangquanghai** [comment]
Thanks thugic , jlevers
