### ISSUE TITLE
How to call a report on sandbox for testing?

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#168]
Dear Jlevers,
We use your library to call GET_FLAT_FILE_OPEN_LISTINGS_DATA report is ok 
but We try it on sand box, by update "endpoint" =>Endpoint::NA_SANDBOX),
it said : [{"code":"InvalidInput","message":"Could not match input arguments"}]
How to call it on sand box environment
Thanks

**Comment by jlevers** [comment]
The sandbox only accepts very particular inputs and returns pre-specified outputs. You can see the request/response information for the `createReport` sandbox call in this part of the Reports API JSON model: https://github.com/amzn/selling-partner-api-models/blob/f208226f6a73d1ef332d5b4e0839dc9b17f4a93d/models/reports-api-model/reports_2021-06-30.json#L376

There's also more info about using the sandbox in the developer guide, [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox).

I'm closing this issue because it isn't related to this library, but if you have more questions, feel free to continue to respond in this thread.
