### ISSUE TITLE
It appears that  report returns the same data for special marketplace, disregarding the marketplaceIds parameter.

### ISSUE THREAD

**Issue by suofiya** [jlevers/selling-partner-api#173]
When requesting GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL report and specifying a marketplaceIds filter, this filter gets completely ignored and the data from all marketplaces is returned.

Is it a bug of SP API? 
Do you have some methods to solve this problem?

**Comment by jlevers** [comment]
I think it's an SP API bug, because I've always experienced this (even before I wrote this library). In my experience, for many (but not all) reports, the report will contain data from all marketplaces in the region (NA/EU/FE) regardless of which `marketplaceIds` you specify. I haven't found a solution to that problem.

One related note, in case it's helpful -- when uploading a feed, the feed does seem to be properly constrained by the `marketplaceIds` given.
