### ISSUE TITLE
Can not retrieve product customisation notes

### ISSUE THREAD

**Issue by Vitaly-A-Ivanov** [jlevers/selling-partner-api#182]
Hi. I'm building the application for the cake toppers factory using sp-api.  Almost all of their products suppose to have customer customisations before an order is placed ( aka 'personalised name' or other options..). 
How can I get this information from the response? I tried to use functions from the OrdersApi, but this information is missing for some reason:/

**Comment by jlevers** [comment]
I believe that you can get product customization data by passing `$data_elements = ['buyerInfo']` into `getOrderItems`, and then retrieving the `buyerInfo` attribute of each order item (more documentation on what the `buyerInfo` object looks like [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#itembuyerinfo)). If you pass in a value for `$data_elements`, the library will automatically generate an RDT and use it in the `getOrderItems` request.

That said, I think that you need access to the Direct-to-Consumer Shipping role in order to get that `BuyerInfo` object, because it's considered PII. Feel free to give it a try and see what happens, but I don't think it's going to work if you don't have access to PII.

**Comment by Vitaly-A-Ivanov** [comment]
Thanks, jlevers, for your reply. 

I thought the same, and I applied for PII access extending the current form for restriction data. 
Still waiting for the answer from Amazon 🤞

Even without passing dataElements, I'm getting buyerInfo, but as an empty object in a response, so I believe it should be there 🤞

Will see. Otherwise, I will send the enquiry to their support.

Let you know later when I get more info 🤝

**Comment by jlevers** [comment]
Yep, getting an empty `buyerInfo` object when you don't have PII access is standard. The same is true for me when I'm using credentials without PII access.

**Comment by jlevers** [comment]
@Vitaly-A-Ivanov I'm going to close this because it sounds like this is a PII access issue, not a library issue. Please feel free to reopen this issue if you need more help.
