### ISSUE TITLE
Listings API: `getListingsItem` doesn't seem to honour the marketplace IDs array

### ISSUE THREAD

**Issue by thugic** [jlevers/selling-partner-api#225]
When calling `getListingsItem` on `ListingsApi`, I get a response with only one marketplace in the `summaries` array, despite passing in multiple marketplace IDs as a request parameter.

I double checked, and the SKU is listed on 3 different marketplaces, and each one of their IDs has been passed to the request.

I am not sure if it's the library that's not serialising the request correctly, or is the SP-API that's broken, so, this is more of a request for somebody to check on their end, so we can figure out where the issue lies.

If it turns out it's an issue on SP-API, I'll open a ticket there.

Thanks in advance for any insights on this.

Cheers.

**How to reproduce:**

```php
$config = YOUR_CONFIG_DATA;
$api = new Api\ListingsApi($config);

$sellerId = 'YOUR_SELLER_ID';
$sku = 'YOUR_SKU'; // Make sure it's listed in more than one marketplace!
$marketplaceIds = 'MULTIPLE_MARKETPLACE_IDS'; // Make sure they match the item listings!
$includedData = 'summaries';

$response = $api->getListingsItem($sellerId, $sku, $marketplaceIds, null, $includedData);

print_r($response);

/*
[OUTPUT]

{
   "sku":"N******5",
   "summaries":[
      { .... } <---------- ONLY ONE MARKETPLACE
   ],
   "attributes":{
      // .....
   },
}
 */
 ```

**Comment by jlevers** [comment]
Interesting point, I'm seeing the same behavior. I'm pretty sure the library is serializing the marketplaces correctly, because I think that we'd get an error back from Amazon if it wasn't (rather than having missing data). Note that the list of marketplace IDs is supposed to be formatted as a comma-separated string for this call instead of an array (e.g., `'ATVPDKIKX0DER,A2EUQ1WTGCTBG2,A1AM78C64UM0Y8'`) but the response still only contains info for a single country even with the marketplace IDs formatted correctly.

I recommend opening an issue in the main docs repository or creating a support case on Seller Central.

**Comment by thugic** [comment]
Yeah, I already tested with comma separated values, and the output is the same: it picks the first marketplace ID and honours only that one.

Thanks for taking the time to confirm this being an issue for you as well.

I'll file a support case on Seller Central.

Cheers, and thanks for this great package!
