### ISSUE TITLE
Error Code "InvalidInput" in patchListingsItem() Call Response

### ISSUE THREAD

**Issue by smpltech** [jlevers/selling-partner-api#240]
when I call the patchListingsItem() api to update the product quantity I get the response as

[400] { "errors": [ { "code": "InvalidInput", "message": "Request has missing or invalid parameters and cannot be parsed.", "details": "" } ] }

with the code like

```
$data = [
                "productType" => "MATTRESS_COVER",
                "patches" => [
                        "op" => "replace",
                        "path" => "/attributes/fulfillment_availability",
                        "value" => [                    
                            "quantity" => 2                    
                        ]
                ]
    ];

 $body = new \SellingPartnerApi\Model\Listings\ListingsItemPatchRequest($data);

 $result = $apiInstance->patchListingsItem($seller_id, $sku, $marketplace_ids, $body, $issue_locale);

 print_r($result);

} catch (Exception $e) {
    echo $e->getMessage(), PHP_EOL;
}
```

can you suggest error cause and the solution for this? Thanks

**Comment by jlevers** [comment]
Hey @smpltech -- I think the problem is that each item in the `patches` array should itself be a `PatchOperation` object. Try this and see if you have any better luck:

```php
$data = [
    "productType" => "MATTRESS_COVER",
    "patches" => [
        new \SellingPartnerApi\Model\Listings\PatchOperation([
            "op" => "replace",
            "path" => "/attributes/fulfillment_availability",
            "value" => [                    
                "quantity" => 2                    
            ]
        ])
    ]
]);

$body = new \SellingPartnerApi\Model\Listings\ListingsItemPatchRequest($data);
$result = $apiInstance->patchListingsItem($seller_id, $sku, $marketplace_ids, $body, $issue_locale);
print_r($result);
```

**Comment by smpltech** [comment]
Getting the same error..... Thanks for trying @jlevers

**Comment by jlevers** [comment]
What are you passing for the other values? (`$seller_id`, `$sku`, `$marketplace_ids`, `$issue_locale`)

**Comment by smpltech** [comment]
Following are the representative values for your reference

$seller_id = "AAAAAAAAAA123";
$sku = "PROD-SKU";
$marketplace_ids = ["A21TJRUUN4KGV"];
$issue_locale = "en_US";

**Comment by smpltech** [comment]
Is this functionality (inventory update) using patchListingsItem() api working at your end @jlevers ?

**Comment by jlevers** [comment]
I hadn't used it myself before, because I don't personally sell anything on Amazon and haven't had a reason to use this call in a client project, but I just created a test listing on my personal account, did some testing, and got the call working like so:

```php
$data = [
    'product_type' => $product_type,
    'patches' => [
        new SellingPartnerApi\Model\Listings\PatchOperation([
            'op' => 'replace',
            'path' => '/attributes/fulfillment_availability',
            'value' => [
                [
                    'quantity' => 2,
                    'fulfillment_channel_code' => $your_fulfillment_channel_code,  // If merchant fulfilled, should be 'DEFAULT'
                ],
            ],
        ]),
   ],
];

$result = $api->patchListingsItem(
    $seller_id,
    $sku,
    $marketplace_ids,
    new SellingPartnerApi\Model\Listings\ListingsItemPatchRequest($data),
    $issue_locale
);
print_r($result);
```

Your product type may not be supported by the SP API yet, so if you get an error response related to that, use the `searchProductTypes` endpoint to find supported product types related to your product that you can pass in `product_type`. Once you find a working product type, you can get the product type JSON schema by calling the `getProductTypeDefinitions` endpoint and going to the URL in the `schema` key of the response. That document is what told me that the `fulfillment_channel_code` property was required for the `fulfillment_channel` attribute.

**Comment by smpltech** [comment]
ya checked with the searchDefinitionsProductTypes() and my Product Type is not present in the response body, This might be the case I think. I have a opened support ticket with amazon support. Thanks for your kind support @jlevers

**Comment by jlevers** [comment]
Even if your product type isn't supported yet, a broader one that encompasses the product type you care about might be available (i haven't actually checked this, but for example `BEDDING` instead of `MATTRESS_COVER`), and you should be able to change the quantity that way since `fulfillment_availability` is an attribute that I believe is present in every product type.

**Comment by shirushi-dev** [comment]
@jlevers 

Thank you as always.

 Does "path" exist other than "attributes"?
And where can I find it?

**Comment by jlevers** [comment]
As far as I know, `path` always starts wtih `/attributes`.

> And where can I find it?

Check what I said about the product type JSON schema two comments ago (https://github.com/jlevers/selling-partner-api/issues/240#issuecomment-1100667172).

**Comment by shirushi-dev** [comment]
@jlevers 
thank you!
I will confirm!
