### ISSUE TITLE
STS queries rate exceeding issue

### ISSUE THREAD

**Issue by valkan07** [jlevers/selling-partner-api#278]
Hi everyone,

we observe such exceptions in case of a lot of queries

```
2022-05-11 07:32:12 [-][-][-][error][application] Catch exception: Error executing "AssumeRole" on "https://sts.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://sts.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling (truncated...)
 Throttling (client): Rate exceeded - <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>f9dc6495-9462-47ce-8b0e-b385f24ee61c</RequestId>
</ErrorResponse>
```

As a solution need the possibility to provide roleCredentials through the configuration in order to implement the caching for queries to STS because of an expiration time for credentials is 1 hour.

Thanks.

**Comment by jlevers** [comment]
Hey @valkan07, I think this is a problem that very, very few people will run into. If you want to open a PR addressing the problem I would welcome that, but I'm probably not going to fix this myself. You also could change your SP API application to use an IAM user ARN rather than an IAM role ARN, at which point this issue would become irrelevant.

Let me know if you plan to open a PR -- otherwise, I'll close this issue.

**Comment by jlevers** [comment]
@valkan07, since I haven't heard from you, I'm going to close this. Feel free to reopen if you want to submit a PR related to this.
