### ISSUE TITLE
Problems with functions that receive Array<string> parameter for SKUs

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#304]
I found an issue for a few functions that accept an array of SKUs as a parameter, like getPricing and getCompetitivePricing.

The problem shows up when some of the SKUs has spaces, hashtag, quotes, etc.

There is a few reports similar to this one (not the same) at https://github.com/amzn/selling-partner-api-docs/issues/742, https://github.com/amz-tools/amazon-sp-api/issues/63 and https://github.com/amzn/selling-partner-api-docs/issues/1400

My findings so far:

- If the function uses the SKU in the path it is working
- if the function uses sku as a string parameter it works
- if the function uses an array of skus as parameter, it fails

For some reason, seems like amazon is expecting (for the last case), a double encoding of the parameter.

I know it is amazon fault and not from your API, I already solved the problem by just encoding the parameter in my code before passing it to the API, but maybe patching the API is a better solution? LMK

**Comment by jlevers** [comment]
Hey @0xSekar -- since your solution is working for you, I'm not going fix this in the library, for two reasons:
1. 95% of this library is autogenerated from JSON models, so adding special fixes to certain calls takes longer than it might seem at first glance
2. I'm hopeful that Amazon will fix this problem eventually, because it keeps cropping up for so many people

Sorry to not be of more help here, and I appreciate the bug report! I'm guessing other people will find this issue helpful.

**Comment by 0xSekar** [comment]
Hi @pawan1793. I solved it just by encoding the array elements before sending it to the library (that will encode it once again):
`$skus[] = rawurlencode("<sku with spaces or other special char>");`
Then this $skus array is used in the call and works as expected
