### ISSUE TITLE
[question] Signing requests

### ISSUE THREAD

**Issue by AlexeyKosov** [jlevers/selling-partner-api#344]
If this library already depends on [aws/aws-sdk-php](https://github.com/aws/aws-sdk-php), why would not it use [AWS' SignatureV4](https://github.com/aws/aws-sdk-php/blob/master/src/Signature/SignatureV4.php) for signing requests? It could be added as a middleware for Guzzle. Or are there any key features in own implementation of [AuthorizationSigner](https://github.com/jlevers/selling-partner-api/blob/main/lib/AuthorizationSigner.php)?

**Comment by jlevers** [comment]
the official SDK was added after i'd already written the signing logic (i needed it for STS), so i haven't looked into using it for signing requests. that said, i'm guessing the process of selecting the correct set of credentials based on the request type (grantless, standard, RDT, etc) would be more challenging if i were to use the SDK rather than my custom logic.
