### ISSUE TITLE
developer  win10  apache  show  trace:  curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*

### ISSUE THREAD

**Issue by fangdashng** [jlevers/selling-partner-api#377]
## Problem description:
when  use  the  getOrders

## Error:
curl_setopt_array(): cannot represent a stream of type Output as a STDIO FILE*
            $conf = array_replace($conf, $options['curl']);
        }

        $conf[CURLOPT_HEADERFUNCTION] = $this->createHeaderFn($easy);
        $easy->handle = $this->handles
            ? array_pop($this->handles)
            : curl_init();
          
        curl_setopt_array($easy->handle, $conf);

        return $easy;
    }

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
I'm not sure what's going on here -- it's not clear to me from your error/code what the context is. That said, I'm fairly confident it's not an issue with the library since I've never seen any error like it before and I'm not directly using curl anywhere in the library. I'm going to close this issue, but if you're still having this problem and want to update the issue with more information, I'm happy to try to help you.
