### ISSUE TITLE
Use APIS for all matketplaces

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#423]
Hi All,
I'm reviewing some softwares, but not all stores are added or some can be added new.  After we finish the APIs we need, can't we use them for the whole marketplaces?  what kind of problem is there or how can we have a problem?

Kind Regards

**Comment by RoanOak127** [comment]
The problem I've run into with my software is the Financial Event's aren't able to be queried with specific Marketplaces. I have customers who sell in most of Europe but when they want to look at Advertising Fees for just a single marketplace they have to manually check with their own records because Financial Events will pull fees for every marketplace the merchant sells in, in one document and not tell you which marketplace they're for. 

You can query marketplaces for Orders, you can kind of do it for Settlement Reports and Return Adjustment Reports but both of those don't actually filter it out but will tell you something like Amazon.nl or the marketplaceId somewhere so it's easy to make your own code and filter it out. But Financial Events have neither of those for some of their Events so you're just stuck with all the data.

**Comment by Kernel1453** [comment]
Thank you @RoanOak127
