### ISSUE TITLE
Notification API

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#425]
Hello,
I am creating a new sqs on aws.amazon.com then trying to create a new destination for a region and subscription. But when i try to use createdestination it is trying to create new sqs. When i send my sqs as parameter for create destination, it returns already exists. 

I have a sqs on aws and want to create destinations for 3 regions. Then i will create my subscriptions for any_offer_changed as per users marketplaces.

What i am missing while using this api?

**Comment by jlevers** [comment]
What happens when you call [`getDestinations`](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-reference#getdestinations)? Does a destination with your SQS ARN already exist? If so, you should be able to use that destination ID with the [`createSubscription`](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-reference#createsubscription) call to subscribe to the `ANY_OFFER_CHANGED` notification.

**Comment by Kernel1453** [comment]
Fixed by Amazon
