### ISSUE TITLE
Orders API v0, ConfirmShipment - feature request

### ISSUE THREAD

**Issue by hurjaJukka** [jlevers/selling-partner-api#489]
Hey,

Would love to see following feature from the [OrdersApiv0](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#confirmshipment) .

Regrads, Jukka Korhonen

**Comment by jlevers** [comment]
Released in `v5.7.0`.

**Comment by deisouss** [comment]
We are getting the following error while trying to confirm a shipment:

_Exception when calling OrdersV0Api->confirmShipment: [400] { "errors": [ { "code": "InvalidInput", "message": "PackageReferenceId: is invalid, must be a positive numeric value.", "details": "" } ] }_ 

The object contains the package reference ID, we also try to omit it as we read Amazon will assign one if omit it but it gives the same error.  Sample response with package ID

```
SellingPartnerApi\Model\OrdersV0\ConfirmShipmentRequest Object
(
    [container:protected] => Array
        (
            [package_detail] => Array
                (
                    [package_reference_id] => 2268
                    [carrier_code] => FedEx
                    [shipping_method] => Ground Home Delivery
                    [tracking_number] => 646555175639
                    [ship_date] => 2024-01-27T04:55:15-00:00
                    [order_items] => Array
                        (
                            [0] => Array
                                (
                                    [order_item_id] => 92874624060921
                                    [quantity] => 1
                                )

                        )

                )

            [cod_collection_method] => 
            [marketplace_id] => ATVPDKIKX0DER
        )

)
```

**Comment by j-koopman** [comment]
@deisouss We also encounter this problem. Do you already have a solution?

**Comment by deisouss** [comment]
Not yet, I was trying to trace the dependencies used to create the package details because I thought the data was being posted as a string instead of a number but I found PackageDetail.php and I tried to modify the code there and it didn't do anything, actually it seems the functions on this file are not called, then I captured the data and manually did a replace to convert the package ID to numbers by removing the quotes and it didn't do anything either.

This makes me think that maybe during submit the package_reference_id is actually not being posted/mapped correctly to the Amazon fields but I have not been able to trace it where exactly is located

If you have any clues of what file dependency I should be looking at I can try to do some tests. The weird thing is that Amazon says that the package_reference_id is optional and if omitted they assign a number, so I don't even know where the error message comes from

**Comment by deisouss** [comment]
> @deisouss We also encounter this problem. Do you already have a solution?

Yes, we got it, you can't pass the data as an array, you need to create protected containers, this is how we solved it:

`$order_id = 'your_order_id_here';
$order_items_list = $this->fn_GetOrderItems($order_id);
$order_item = $order_items_list->getPayload()->getOrderItems();
            
$shipment_items = new ConfirmShipmentOrderItem(); 

foreach ($order_item as $item) {
    if( $item['quantity_shipped']> 0) {
        echo "Items in order " . $order_id . " already marked shipped";
        return;
    } else {
    
        $shipment_items->setOrderItemId($item->getOrderItemId());
        $shipment_items->setQuantity($item->getQuantityOrdered());
    }
}

$package_details = new PackageDetail();
$package_details->setCarrierCode('your_carrier_code');       
$package_details->setCarrierName('your_shipping_carrier');
$package_details->setTrackingNumber('your_tracking_number');
$package_details->setShippingMethod('your_shipping_method');
        
$package_details->setPackageReferenceId('1');
$package_details->setShipDate(gmdate('Y-m-d\TH:i:s\Z'),strtotime('your_ship_date')); 
$package_details->setOrderItems([$shipment_items]); //must be in brackets to make it an array

$payload = new ConfirmShipmentRequest();
$payload ->setPackageDetail($package_details);
$payload ->setMarketplaceId('your_market_placeid');

$apiInstance = new OrdersV0Api($this->config); //your config settings

try {
    $apiInstance->confirmShipment($order_id, $payload);
    echo "Order " . $order_id . " Fulfilled";
    return; 
} catch (Exception $e) {
    echo $order_id . ' Exception when calling OrdersV0Api->confirmShipment: ', $e->getMessage(), PHP_EOL;
    return; 
}`

**Comment by alvaroSC2405** [comment]
Thanks for the reply. I also have the same error.
But the answer you propose is from Amazon's MWS library. It will stop working on March 31, 2024. 
Am I wrong?
I use the jlevers/selling-partner-api library and I found this error.
This is my code in case someone can help me. Thank you very much again

require_once $_SERVER["DOCUMENT_ROOT"]."/core/amazon/configuration.php";

$apiInstance = new SellingPartnerApi\Api\OrdersV0Api($config);
$order_id = "407-0298474-4483561"; // string | An Amazon-defined order identifier, in 3-7-7 format.

 $marketplace_ids = 'A1RKKUPIHCS9HS';


$data = [
    'marketplace_id' => $marketplace_ids,
    'package_reference_id' => '12345',
    'carrier_code' => 'Others',
    'carrier_name' => 'Envialia',
    'tracking_number' => '0003220153290155',
    'ship_date' => '2024-03-14T08:00:00Z',
    'order_items' => [$dataItems] 
];

$dataItems=["order_item_id"=>"36571763275002",
            "quantity"=>"2"
];

$payload = new \SellingPartnerApi\Model\OrdersV0\ConfirmShipmentRequest($data); // \SellingPartnerApi\Model\OrdersV0\ConfirmShipmentRequest | Request body of confirmShipment.

try {
    $apiInstance->confirmShipment($order_id, $payload);
} catch (Exception $e) {
    echo 'Exception when calling OrdersV0Api->confirmShipment: ', $e->getMessage(), PHP_EOL;
}

**Comment by alvaroSC2405** [comment]
Please can you attach an example of what your $payload variable would look like?
I have tried to simulate your method. And now I find this error

  _**Exception when calling OrdersV0Api->confirmShipment: [400] { "errors": [ { "code": "InvalidInput", "message": "1 validation error detected: Value \u0027\u0027 at \u0027marketplaceId\u0027 failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9]{1,50}$", "details": "" } ] }**_ 

I guess I'm passing the $payload parameter wrong in the request.
This is my $payload code:

`object(ConfirmShipmentRequest)#21 (2) { ["packageDetail":protected]=> object(PackageDetail)#20 (6) { ["carrier_code":protected]=> string(6) "Others" ["carrier_name":protected]=> string(8) "Envialia" ["tracking_number":protected]=> string(16) "0003220153290155" ["package_reference_id":protected]=> string(1) "1" ["ship_date":protected]=> string(20) "2024-03-14T08:00:00Z" ["order_items":protected]=> NULL } ["marketplace_id"]=> string(14) "A1RKKUPIHCS9HS" }`

**Comment by deisouss** [comment]
@alvaroSC2405 

> But the answer you propose is from Amazon's MWS library. It will stop working on March 31, 2024.
> Am I wrong?

The code I posted is for jlevers, not MWS, it calls all the functions from jlevers. Also you might want to delete that comment because you are doing exactly what I said it doesn't work, which is passing the data in the form of an array ($data, $dataItems) , I don't know why that doesn't work, you have to create the container firs like this

`$data= new PackageDetail();`

Then you add the information to it.

> Please can you attach an example of what your $payload variable would look like?
> I have tried to simulate your method. And now I find this error

In your code you are passing the marketplace_id as an array again, see my example again, you create a new new ConfirmShipmentRequest() then add the package details and then the MarketplaceId in this format:

```
$payload = new ConfirmShipmentRequest();
$payload ->setPackageDetail($package_details);
$payload ->setMarketplaceId('your_market_placeid');
```

**Comment by deisouss** [comment]
Sorry I am not an expert on jlevers so I don't know where your mistake can be at, the end of your code seems to be correct except that you are omitting **setOrderItems** I think this is a required field. In my sample code I use a function I made called fn_GetOrderItems (copy below) which gets the Items on the Order, with this you can get the required itemId and quantity.

```
private function fn_GetOrderItems($order_id){
	$apiInstance = new OrdersV0Api($this->config);
	try {
		$result = $apiInstance->getOrderItems($order_id);
		return $result;
	} catch (Exception $e) {
		echo 'Exception when calling OrdersV0Api->getOrderItems: ', $e->getMessage(), PHP_EOL;
	}
}
```

I see now that you are passing the marketplaceID correctly, so the only mistake might be not passing the items as **order_items** is null

**Comment by deisouss** [comment]
Did you see the note that I have for the items that they must be in brackets?
_$package_details->setOrderItems([$shipment_items]); **//must be in brackets to make it an array**_

Here is the Payload response before posting:

SellingPartnerApi\Model\OrdersV0\ConfirmShipmentRequest Object
(
    [container:protected] => Array
        (
            [package_detail] => SellingPartnerApi\Model\OrdersV0\PackageDetail Object
                (
                    [container:protected] => Array
                        (
                            [package_reference_id] => 1
                            [carrier_code] => Conway
                            [carrier_name] => 
                            [shipping_method] => Freight Truck
                            [tracking_number] => XXXXXXXX
                            [ship_date] => 2024-03-14T14:53:16Z
                            [ship_from_supply_source_id] => 
                            [order_items] => Array
                                (
                                    [0] => SellingPartnerApi\Model\OrdersV0\ConfirmShipmentOrderItem Object
                                        (
                                            [container:protected] => Array
                                                (
                                                    [order_item_id] => XXXXXXXX
                                                    [quantity] => 1
                                                    [transparency_codes] => 
                                                )

                                        )

                                )

                        )

                )

            [cod_collection_method] => 
            [marketplace_id] => ATVPDKIKX0DER
        )

)

**Comment by deisouss** [comment]
@alvaroSC2405 I already posted the code. To simplify things what I would recommend is saving all the data to variables **first**, for example anything that I have in my code as "your_xxxx" save it to a variable first then replace it to what is on my code.

The only change will be to this part of the code because I am getting them from my function, but you can save them to variables with your code:

```
$shipment_items->setOrderItemId($item->getOrderItemId());
$shipment_items->setQuantity($item->getQuantityOrdered());
```

So disregard the for loop I made and simply do it like this:

```
$shipment_items = new ConfirmShipmentOrderItem();
$shipment_items->setOrderItemId('your_OrderItemId');
$shipment_items->setQuantity('your_Quantity');
```

I struggled with this for a long time, and this is finally working so I know my solution works, just save your data to variables first, then replace it to my code. If you get an error, read what the error says to try to pinpoint what area of the secure container is wrong

Please also note that **$apiInstance = new OrdersV0Api($this->config);** should have **your** configuration settings, we get them this way, your code might get them differently so you have to replace **$this->config** to your code

**Comment by deisouss** [comment]
@alvaroSC2405 the code that you are requesting we paid to be made, sorry I cannot just post it here. Reach me if you would like to get them for a fee
