### ISSUE TITLE
Add support to use proxy server

### ISSUE THREAD

**Issue by chelid** [jlevers/selling-partner-api#52]
Thanks for a very useful library! 
Can you possibly add an option to insert proxy host, user and password on the configuration options (or somewhere else..), and have the GuzzleHttp\Client use them to make requests?

**Comment by jlevers** [comment]
You're welcome, glad it's been useful for you!

I'll add this to the list of requested features -- it may be a while before I get to it, but I'll do my best :)

**Comment by jlevers** [comment]
Hi @chelid -- sorry for the (very) long delay here. I'm realizing now that you should be able to handle this by passing in a custom Guzzle client into the constructor for a given API class, like so:

```php
$customClient = new GuzzleHttp\Client(/* *** */);
$config = new SellingPartnerApi\Configuration([ /* ... */ ]);
$api = new SellingPartnerApi\Api\SellersApi($config, $customClient);
```

If this issue is still relevant to you, please let me know if that has the effect you were looking for.

**Comment by jlevers** [comment]
I'm going to close this for now -- if anyone needs functionality that isn't covered by my previous comment, please feel free to reopen.
