### ISSUE TITLE
post_product_pricing_data  not being updated prices

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#534]
Dear All,

I have a big problem but not about package. I create feed id, document id and get url. So when we upload document url content returns successful message. i am checking prices but not being updated. Have you ever had an issue like this? I created a case for this to amazon but they havent answered yet.

Please help me if you have any idea.
Best Regards

**Comment by statsmarketing** [comment]
I currently have same issue and am investigating it now.

**Comment by dartheditous** [comment]
> So when we upload document url content returns successful message. i am checking prices but not being updated. 

If you're stopping after uploading the document, then you're not completing the process. You have to create the feed next - this tells Amazon to process the uploaded document in accordance with the feed type you specify.

This will give you the feed ID, which you can then optionally check the status of and get a report on once the feed has finished processing.

**Comment by Kernel1453** [comment]
> 

Thank you very much for your Quick response but we complete process so we get url content as successfull. I sent price update for 3 items today. 1 item immediately  updated. Other 2 items updated after many times ( about 3 hours) same codes and processes. Today worked but very very late. Still i dont know what we can do to overcome this.

**Comment by jlevers** [comment]
I recommend opening a case with Amazon about this, although unfortunately I'm guessing they're going to tell you that there isn't anything they can do (🙄). I've had this issue before too, although I've found that the new prices usually take around an hour to show up.

I'm going to close this issue since it isn't a problem with the library itself, but feel free to keep responding here if you want/need more support.
