### ISSUE TITLE
API call for parent categories associated with a product or ... ?

### ISSUE THREAD

**Issue by jmichaelterenin** [jlevers/selling-partner-api#56]
On this Github page for the Selling Partner API docs: https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md

there's an operation called: listCatalogCategories, that provides the parent-child category list associated with a product listing. I couldn't find the API call for this in your PHP library, can anyone assist? 

Basically, I'm looking for a more descriptive subcategory name for the product listing other than what: getCatalogItem provides with the 'productTypes' dataset. it might be useful to get this category tree (complete with ids?) outside of the API, since it seems pretty fair to say the category tree isn't changed very often. 

Thanks in advance for any help on this!

**Comment by jmichaelterenin** [comment]
Below is an example of the product tree (and last sub-category) that is available for the product type: COMPUTER_DRIVE_OR_STORAGE

![ProductTree](https://user-images.githubusercontent.com/8676120/125178857-6543f680-e19d-11eb-9de7-404e14ab7d3c.png)

**Comment by jmichaelterenin** [comment]
UPDATE: 
So I did some code inspection and saw that the operation: listCatalogCategories isn't currently integrated.
I tried making the call myself, and I come up with a status Code: 403 Access Denied.

Here's the Request data being sent, first the getCatalogItem operation:

```
 /catalog/2020-12-01/items/B00C9TEOWU
marketplaceIds=ATVPDKIKX0DER&includedData=images%2Csummaries%2CproductTypes%2CsalesRanks&locale=en_US
{"User-Agent":"jlevers/selling-partner-api/3.0.5 (Language=PHP)","Accept":"application/json","Content-Type":"application/json","Host":" sellingpartnerapi-na.amazon.com"} 

/catalog/2020-12-01/categories
marketplaceId=ATVPDKIKX0DER&asin=B00C9TEOWU
HEADERS: {"User-Agent":"jlevers/selling-partner-api/3.0.5 (Language=PHP)","Accept":"application/json","Content-Type":"application/json","Host":" sellingpartnerapi-na.amazon.com"}

```
I've tried variations for the query variables, like 'marketplaceIds' and 'Asin', with no change.
Jesse, hoping to hear from you if you have any insight, thanks!

**Comment by jlevers** [comment]
Hi @jmichaelterenin, thanks for reporting.

Amazon put out a set of models for a newer version of the Catalog API, which I assumed were ready to go, and integrated the calls from those newer models into this library. The newer Catalog API doesn't include the `listCatalogCategories` call (I believe they integrated the result of that call into one of the other Catalog API operations?).

It looks like maybe those newer models weren't actually deployed yet, which is why calling the newer endpoints is resulting in a `403`. I commented on the issue you created in the `amzn/selling-partner-api-docs` repository to ask Amazon to clarify the status of these endpoints. Once I've heard back from them, I'll have a better sense of how to go about fixing this problem.

**Comment by jmichaelterenin** [comment]
Hi Jesse,
Finally found what I was looking for: https://www.youtube.com/watch?v=SfX9mRdR9Bw
Turns out this info is available for download, as opposed to accessing it through the API,  as I thought it might be, considering it's not changed very often at all.

Very helpful Amazon tech support (commenting on their response to me) ; )
