### ISSUE TITLE
Unable to Access PII Data for Client Accounts - Possible Missing Connection Between Seller Central Accounts

### ISSUE THREAD

**Issue by Julian3004** [jlevers/selling-partner-api#601]
Hello,

I am a global developer and have implemented the SP-API into our system. Everything works fine for our own Seller Central account. However, when trying to access PII data for our clients who have a different Seller Central account, we encounter the following error:

`TokensV20210301Api->createRestrictedDataToken: [400] { "errors": [ { "code": "InvalidInput", "message": "Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]", "details": "" } ] }
`

I have checked the permissions and everything appears to be in order. Here's the code snippet I'm using:

```php
$aAccessData = getAwsAccessData($db_shop);

$config = new SellingPartnerApi\Configuration([
    'lwaClientId' => $aAccessData['lwaClientId'],
    'lwaClientSecret' => $aAccessData['lwaClientSecret'],
    'lwaRefreshToken' => $aAccessData['lwaRefreshToken'],
    'awsAccessKeyId' => $aAccessData['SP_API_ACCESS_KEY'],
    'awsSecretAccessKey' => $aAccessData['SP_API_SECRET_KEY'],
    'endpoint' => $aAccessData['SP_API_ENDPOINT'],
    'roleArn' => $aAccessData['SP_API_ROLE_ARN']
]);


$apiInstance = new SellingPartnerApi\Api\TokensV20210301Api($config);
$body = new \SellingPartnerApi\Model\TokensV20210301\CreateRestrictedDataTokenRequest(); // \SellingPartnerApi\Model\TokensV20210301\CreateRestrictedDataTokenRequest | The restricted data token request details.

$body->setRestrictedResources([
		'method' => 'GET',
		'path' => '/orders/v0/orders',
		'dataElements' => ['buyerInfo', 'shippingAddress']
]);

try {
  $result = $apiInstance->createRestrictedDataToken($body);
  print_r($result);die;
} catch (Exception $e) {
  echo 'Exception when calling TokensV20210301Api->createRestrictedDataToken: ', $e->getMessage(), PHP_EOL;
}
``` 

I suspect that there might be no connection between my Seller Central account (as a global developer) and my clients' Seller Central accounts. The only connection that seems to exist is through the AWS Developer Portal, but I haven't found any option there to link my Seller Central account.

Can anyone help troubleshoot this issue or provide insights into what I might be missing or how to properly establish this connection?

Thank you in advance.

**Comment by jlevers** [comment]
You'd need to put your clients through the SP API's OAuth flow in order to make calls on their behalf, using your account permissions. In that case you'd be using your SP API credentials, except with a refresh token that's specific to their account.

There's more info on how authorization with the SP API works in the official docs, [here](https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications). Just to warn you: getting approved for PII access as a public developer is a REALLY big pain. I [created a discussion](https://github.com/amzn/selling-partner-api-docs/discussions/3231) about this problem in the SP API issues repository, but haven't gotten any real response from Amazon.

**Comment by Julian3004** [comment]
Thank you for your prompt response @jlevers.

Indeed, it was quite a challenging process to get approval for PII access. It took us three months, but we were finally approved yesterday. So, that particular issue is now resolved for us.

I'll proceed with implementing the oAuth flow as described in the documentation. I was under the impression that the refresh token would suffice, but I now understand that a full oAuth integration is required to make calls on behalf of our clients.

On that note, I have a question: How exactly is the token passed in this scenario? Do we provide the token in place of the refresh token, or what does the configuration look like in this case?

Thank you for your guidance and clarification.

**Comment by jlevers** [comment]
Just to double-check – are you approved for PII as a public developer, rather than as a private developer? Because I believe the OAuth flow won't work if you're not a public developer. If so, congrats, that's no small feat.

To make call,s you just need to pass the refresh token that you generated for the client via the OAuth flow in place of your personal refresh token.

Also note that until your application is listed on the Selling Partner Appstore, you're limited to a maximum of 25 OAuth-authenticated clients.

**Comment by Julian3004** [comment]
Thank you for your insights.

Correct, we have access as a public developer. A clear indication of this is that we now have the option to list our application in the Selling Partner Appstore. Moreover, in the application section within Seller Central, I can see the two fields for oAuth: "OAuth Login URI" and "OAuth Redirect URI".

I still have a question. Is the oAuth flow the only way to proceed? The way I've implemented it currently is that our customers copy the refresh token from their Seller Central account and input it into the credentials section in our system. Hence, I assumed this would be sufficient. [Here's the link](https://developer-docs.amazon.com/sp-api/docs/authorize-vendor-groups-for-application-access) to the method we are currently using

Would appreciate your thoughts on this.

**Comment by jlevers** [comment]
Sorry for taking a while to respond. I didn't realize you were developing Vendor applications – the Vendor flow is a bit different. What solution worked for you?
