### ISSUE TITLE
Please update "illuminate/support" package to support laravel 11.

### ISSUE THREAD

**Issue by Abbotton** [jlevers/selling-partner-api#676]
Please update "illuminate/support" package to support laravel 11.

![image](https://github.com/jlevers/selling-partner-api/assets/16308633/cb18bd77-e478-4673-8e46-9cbd73d0522f)

Thank you Jesse.

**Comment by wooly-booly** [comment]
Please update "illuminate/support" package to support  symfony 7
![Uploading Screenshot 2024-04-14 at 12.59.09.png…]()

**Comment by jlevers** [comment]
This is because `laravel-zero/framework`, which `highsidelabs/saloon-sdk-generator` requires, has not been upgraded to be compatible with Laravel 11. I think the right move here is to just figure out how to make `highsidelabs/saloon-sdk-generator` a dev dependency instead of a regular dependency, so that issues with dev packages don't effect regular users.

(Related to some of the points raised #679)

**Comment by torro-uk** [comment]
Is there any update on how to get the package to work with laravel 11?

**Comment by jlevers** [comment]
It will fully support Laravel 11 in v7, which will be released soon. Feel free to use `dev-main` in the meantime if you need this update ASAP, although there may be breaking changes made to the branch between now and when v7 is released.

**Comment by jlevers** [comment]
Released in `v7.0.0`.
