### ISSUE TITLE
Migration to v6

### ISSUE THREAD

**Issue by stevenbrookes** [jlevers/selling-partner-api#679]
Hi

Just a couple of points I've come across while migrating to V6.

1.  Using the DTOs.  In V5 for example when I got a Feed back from the Feed endpoint I could then call getProcessingStatus() on the returned object.  Now once I've called dto() on the response and also type hinted it in my IDE to Feed I have to call ->processingStatus.  I'll have to make that change  for every data access in our existing code which feels rather wasteful.  Any chance we could have getters or magic getter to avoid having to refactor all the code?

2.  Looking at the composer.json there's a couple of dependencies that look to be -dev ones?  Could they be moved the -dev to help slim things down?
- composer/semver
- highsidelabs/saloon-sdk-generator
- illuminate/support

Other than that so far migration looks strightforward.
Thanks
Steve

**Comment by misterakko** [comment]
I'll chime in with a very small pet peeve of mine.

I always like to report to the end user the names and versions of every library I use. This is done so that in case of an error report, the end user can easily paste into a ticket a bunch of information about his configuration.

With the library v5 we had ->getUserAgent() which did the job
I can't find anything similar in v6

**Comment by jlevers** [comment]
Thanks for the comments yall.

@stevenbrookes I moved almost all requirements to dev dependencies, thanks for the suggestion. I decided not to continue supporting the accessor methods – sorry that it's a pain to update them.

@misterakko there's now a `->getUserAgent()` method on `SellingPartnerApi`.
