### ISSUE TITLE
Invalid value 'GB_VOEC' for 'deemed_reseller_category'

### ISSUE THREAD

**Issue by IoanAndrei97** [jlevers/selling-partner-api#68]
When I'm trying to get the orders from the UK marketplace (A1F83G8C2ARO7P) I'm getting this error `Invalid value 'GB_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS'`

From what I understand this is caused by Amazon changing the API without updating the documentation.

This can be fixed by adding this 2 lines in Model/Orders/OrderItem.php

1. `const DEEMED_RESELLER_CATEGORY_GB_VOEC = 'GB_VOEC'` ( line 324, right after `const DEEMED_RESELLER_CATEGORY_UOSS    = 'UOSS'`
2. `self::DEEMED_RESELLER_CATEGORY_GB_VOEC` in `getDeemedResellerCategoryAllowableValues()` method

**Comment by jlevers** [comment]
Hey @loanAndrei97, thanks for reporting!

The other two `DEEMED_RESELLER_CATEGORY_*` values have descriptions associated with them in the `ordersV0.json` Swagger model, [here](https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json#L2498). Would you mind writing a similar description for the `GB_VOEC` option, so that I can keep the documentation complete? I'd write the description myself, but I don't know what that option does.

**Comment by IoanAndrei97** [comment]
Hello @jlevers 
Well, I think it should be something like this:
`
{
  "value": "GB_VOEC",
  "description": "Import one stop shop. The item being purchased is held in the GB for shipment."
},
`

**Comment by jlevers** [comment]
Thanks! This is fixed in `v3.1.1`, which I just released.

**Comment by alexmillman2394** [comment]
Hello,

I am using version ^4.0 and I receive this same error:

`Invalid value 'CA_MPF' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS', 'GB_VOEC'`

**Comment by widdydev** [comment]
Hi,
when I'm fetching the order items for a GB order I'm receiving an error.
I'm using ^5.6 and still got this issue:
`Invalid value 'GB_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS'`
