### ISSUE TITLE
Support new versions of the Feed and Reports APIs

### ISSUE THREAD

**Issue by markbeazley** [jlevers/selling-partner-api#69]
Amazon have [now released](https://github.com/amzn/selling-partner-api-docs/discussions/1107) updated versions of the Reports and Feed APIs that no longer require encrypting and decrypting of the files on the client side. The old versions are being deprecated in August 2022.

**Comment by jlevers** [comment]
Thanks for noting this -- I'm hoping to get around to updating this in the next couple weeks, but I don't think it's particularly urgent since a) the old version of those APIs won't be deprecated for over a year (as you said), and b) the `Document` class obscures the encryption, so it's not a usability issue.

**Comment by jlevers** [comment]
Added in v3.1.0.
