### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 Documentation Missing

### ISSUE THREAD

**Issue by ssamran15** [jlevers/selling-partner-api#708]
it is really good to see that this package has been updated to accommodate the newer version of FBA Inbound APIs. but I feel that the usage documentation for the said APIs is missing in the library. can you please advice. or point me in the right direction if it is already added in there.

**Comment by jlevers** [comment]
The library's method/parameter naming scheme is built to be as similar to the names in Amazon's official docs as possible, so once you understand the general structure of API classes (e.g., the class you get by calling `$connector->fbaInboundV20240320()`), request classes, and DTOs (docs [here](https://github.com/jlevers/selling-partner-api?tab=readme-ov-file#working-with-dtos)), you should be able to follow the official docs to figure out how to use each of the API methods/DTOs/etc. More info in the README, [here](https://github.com/jlevers/selling-partner-api?tab=readme-ov-file#naming-conventions).

I decided it was too much work (and often, confusing for users) to maintain a whole separate set of docs that are inevitably not as complete/correct as the official docs, since I would have to autogenerate them.

Hope that helps!
