### ISSUE TITLE
OrdersV1 - OrderAcknowledgement items should be OrderAcknowledgementItem

### ISSUE THREAD

**Issue by michalbundyra** [jlevers/selling-partner-api#726]
## Problem description:

Currently in OrderAcknowledgement we expect items to be OrderItem:

https://github.com/jlevers/selling-partner-api/blob/c11c2d66fde26237a31a7df278f28c9388942b1c/src/Vendor/OrdersV1/Dto/OrderAcknowledgement.php#L16

but specification defines `OrderAcknowledgementItem`:

https://github.com/jlevers/selling-partner-api/blob/c11c2d66fde26237a31a7df278f28c9388942b1c/resources/models/vendor/orders/v1.json#L3610-L3616

and we have these DTO created.

It looks like very generic issue with parser, so the code might be wrong in many places.

See: https://github.com/highsidelabs/saloon-sdk-generator/issues/4

**Comment by michalbundyra** [comment]
@jlevers can I ask why it was labeled with v7.x? It is a bug in the current version, and the behaviour is wrong, version 5.x was fine, here it is referencing the wrong object, so it is impossible to use this integration for `OrderAcknowledgement` and probably much more. Thanks 🙌

**Comment by jlevers** [comment]
It's labeled v7.x because I'm going to release the fix in 7.0. I agree that it's a bug in the current version, and it's fixed – the fix is in #731. There have been a number of bugs introduced that weren't present in 5.x, but I'm pretty confident that the overhaul I did for 6.x will result in a better package in the long term. It was impossible for anyone other than me to effectively maintain 5.x Sorry for the inconvenience with v6+ – we're ironing the bugs out.

**Comment by jlevers** [comment]
Released in `v7.0.0`.
