### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by christian71-stack** [jlevers/selling-partner-api#794]
I have now update from version 5 to the current version 7.7.2. 
What is the best way to catch and evaluate errors when calling the API? 
In the old version there was still the ApiException and it no longer exists. 
The pure call or the result does not throw any errors and I want the status code and the message about it.

**Comment by jlevers** [comment]
Now the library will throw a `RequestException` (in practice, usually it's either a `ClientException` or a `ServerException`, which are subclasses of `RequestException) instead of the old `ApiException`. More info on how Saloon, the package behind the newer version of the library, handles exceptions here: https://docs.saloon.dev/the-basics/handling-failures#response-exceptions
