### ISSUE TITLE
403 error, unauthorized

### ISSUE THREAD

**Issue by yassersebai** [jlevers/selling-partner-api#8]
Hi, thank you for this repo.
I am getting a 403 response on a simple getmarketplaceparticipation request, although the selling partner API policy is attached to the rule on which my application is running.

anyhow, I can make a request using the Postman AWS signature method and I am getting valid responses so I am sure my credentials are correct.
any thoughts about this ?

**Comment by jlevers** [comment]
This library supports having the Selling Partner API policy attached to an IAM user, rather than a role. If you attach the SP API policy as an inline policy on your IAM user, I'm guessing your problem will go away.

I'm planning to add support for the role-based approach at some point, but I haven't gotten there yet.

**Comment by yassersebai** [comment]
thank you for your response.

but actually I am still getting the 403 error, even though i had the executeapi policy attached to my user as an inline policy
is there any restrictions about the policy naming i should be aware of?
and in case that i am getting this totally wrong, can you specify the policy name that should be attached to my IAM user

**Comment by jlevers** [comment]
The name of the policy shouldn't matter, but this is what the contents of the policy should be:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}
```

When you created your SP API application in Seller Central, did you use an IAM user ARN or an IAM role ARN?

**Comment by yassersebai** [comment]
an IAM role ARN as was stated in the documentation.

**Comment by jlevers** [comment]
This library is set up to work with a slightly different setup -- as described in the blog post linked to in [this section](https://github.com/jlevers/selling-partner-api#prerequisites) of the README, it's possible to set up your IAM configuration in a way that eliminates the step of setting up a role and assuming that role with an IAM user. Instead, you can attach the `execute-api` permission to an IAM user directly, and use that.

[This issue](https://github.com/amzn/selling-partner-api-docs/issues/128) in the main SP API documentation repo describes the difference between the two methods, as does the blog post I mentioned.

I'm going to add support for the traditional role ARN method in this library at some point, but I haven't gotten there yet. If you create another SP API app with a user ARN instead of a role ARN, this library will work.

**Comment by Nilanth** [comment]
@jlevers 
I am using user ARN, But still, I face this issue?

**Comment by jlevers** [comment]
Would you mind showing your code?

**Comment by Nilanth** [comment]
This what I use. 

`<?php
require_once(__DIR__ . '/vendor/autoload.php');

$api = new SellingPartnerApi\Api\SellersApi();
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}

?>
 `

**Comment by jlevers** [comment]
Do you have access to the `Selling Partner Insights` SP API role?

**Comment by Nilanth** [comment]
Yes have it

**Comment by Nilanth** [comment]
Does SP API doesn't work if the developer account (NA) is deactivated? But I get the response in MWS API with no issues.

**Comment by jlevers** [comment]
If your developer account is deactivated, you won't be able to make requests with the SP API.

**Comment by Nilanth** [comment]
But my MWS API works fine, Can you please share the reference link? as I have not seen reg this in the docs!!!

> If your developer account is deactivated, you won't be able to make requests with the SP API.

**Comment by jlevers** [comment]
When you said your developer account is deactivated, I assumed you were referring to downgrading your Seller account from a Professional to an Individual account, because that's the only action I'm aware of that will deactivate a developer account.

If that's what you're referring to, one of the SP API developers [confirmed](https://github.com/amzn/selling-partner-api-docs/issues/1#issuecomment-692349946) that you need a Professional account to develop SP API applications.

**Comment by Nilanth** [comment]
My account is subscribed to the Professional plan. But my NA marketplace is deactivated.

**Comment by jlevers** [comment]
Gotcha. In my experience, if a marketplace is deactivated, you won't be able to make SP API requests in that marketplace...I'm not sure where this is mentioned in the documentation (if anywhere), but I've run into that problem a couple times before.

Also, if you made your developer account outside of the NA region (e.g., from https://sellercentral.amazon.co.uk instead of https://sellercentral.amazon.com), you may not be able to make requests to the NA SP API endpoint (https://sellingpartnerapi-na.amazon.com). That's an issue I've seen several people run into.
