### ISSUE TITLE
400 Error in CreateInboundShipmentPlanRequest 

### ISSUE THREAD

**Issue by SeintApril** [jlevers/selling-partner-api#83]
I have used body part for creating shipment plan.

$body = new CreateInboundShipmentPlanRequest([
    'ship_from_address' => [
        'Name' => '番屋株式会社',
        'AddressLine1'=> '北屋敷37 打越町',
        'CountryCode'=> 'JP',
        'city' => 'Tokyo',
        'state_or_province_code' => '470-0213'
    ],
    'label_prep_preference' => 'SELLER_LABEL',
    'ShipToCountryCode' => 'JP',
    'inbound_shipment_plan_request_items' => [
        'seller_sku' => 'LG430-BLK260',
        'asin' => 'B097SNP112',
        'condition' => 'New',
        'quantity' => 'int5'
    ]
]);

I've got following error.

Exception when calling FbaInboundApi->createInboundShipmentPlan: [400] { "errors": [ { "code": "InvalidInput", "message": "Invalid SellerSKU specified: SellerSKU must not be empty.", "details": "" } ] }

I've already change as SellerSKU and SellerSku but the error still occcur.

**Comment by jlevers** [comment]
All your keys should be `snake_case`, which I'm guessing is part of the problem. Also, `ship_from_address` should be a `Model\FbaInbound\Address` object rather than an array, and `inbound_shipment_plan_request_items` should be an array of `Model\FbaInbound\InboundShipmentPlanRequestItem` objects. Hope that helps!

**Comment by SeintApril** [comment]
Omg! it does work. I've been stuck in this step for days. Thank you so much for your support.
