### ISSUE TITLE
Developer Docs PII related questions

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#98]
When ReRegistration the developer form for PII access, I came through these questions **1. List the online channels that you support today**, **2. Please list the Amazon programs you intend to support through your application or functionality.**?

Does anyone know what it means by **online channels** and  **Amazon programs you intend to support through your application**?

**Comment by jlevers** [comment]
I believe that *online channels* refers to the eCommerce platforms that your application interacts with -- for a client I once answered something like "Amazon, BigCommerce, Shopify, eBay, and others."

*Amazon programs* could be things like FBA, FBM, Vendor fulfillment, etc.

(These are just my best guesses -- I can't say for sure what the correct answers are.)

I'm going to close this, because it's not actually an issue with the library, but if anyone else wants to add more info here, please feel free.
